baseURL: https://tricitiesmesh.net/
title: Tri-Cities Mesh

menus:
  main:
    - name: MeshMap
      weight: 20
      url: https://map.tricitiesmesh.net/
      target: ""

# cSpell:ignore goldmark github hugo readingtime docsy subdir lastmod pygments linenos catmullrom norsk gu

# Language settings
contentDir: content
defaultContentLanguage: en

enableRobotsTXT: true

# Will give values to .Lastmod etc.
enableGitInfo: true

# Comment out to enable taxonomies in Docsy
# disableKinds: [taxonomy, taxonomyTerm]

# You can add your own taxonomies
taxonomies:
  tag: tags
  category: categories

# Highlighting config
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic: false
# pygmentsOptions: "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: tango

# Configure how URLs look like per section.
permalinks:
  blog: /:section/:year/:month/:day/:slug/

# Image processing configuration.
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style: tango
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax: true

# Everything below this are Site Params

params:
  mapboxToken: pk.eyJ1IjoiZXRoYW5oYXJzdGFkIiwiYSI6ImNtN3Y4YjZkazA4b2cya3B3cGVqdWpnOGIifQ.Lu7fPiHPjQ_bxr4TR33Bjg
  meshmapUrl: https://map.tricitiesmesh.net/
  
  taxonomy:
    # set taxonomyCloud = [] to hide taxonomy clouds
    taxonomyCloud: [tags, categories]

    # If used, must have same length as taxonomyCloud
    taxonomyCloudTitle: [Tag Cloud, Categories]

    # set taxonomyPageHeader = [] to hide taxonomies on the page headers
    taxonomyPageHeader: [tags, categories]

  # First one is picked as the Twitter card image if not set on page.
  # images: [images/project-illustration.png]

  # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
  github_repo: https://github.com/joshuacarmack/tricitiesmesh

  # Specify a value here if your content directory is not in your repo's root directory
  github_subdir: "content"

  # Uncomment this if your GitHub repo does not have "main" as the default branch,
  # or specify a new value if you want to reference another branch in your GitHub links
  github_branch: main

  # Google Custom Search Engine ID. Remove or comment out to disable search.
  # gcs_engine_id: d72aa9b2712488cc3

  # Enable Lunr.js offline search
  offlineSearch: false

  # Enable syntax highlighting and copy buttons on code blocks with Prism
  prism_syntax_highlighting: false

  copyright:
    authors: Tri-Cities Mesh
    from_year: 2025

  # User interface configuration
  ui:
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
    navbar_logo: true
    # Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
    navbar_translucent_over_cover_disable: true
    navbar_class: "bg-primary navbar-dark"
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: false
    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: false

    # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
    # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
    # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
    # add "hide_feedback: true" to the page's front matter.
    feedback:
      enable: false
      # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
      "yes": >-
        Glad to hear it! Please <a href="https://github.com/joshuacarmack/tricitiesmesh/issues/new">tell us how we can improve</a>.
      "no": >-
        Sorry to hear that. Please <a href="https://github.com/joshuacarmack/tricitiesmesh/issues/new">tell us how we can improve</a>.

    # Adds a reading time to the top of each doc.
    # If you want this feature, but occasionally need to remove the Reading time from a single page,
    # add "hide_readingtime: true" to the page's front matter
    readingtime:
      enable: false
  links:
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    user:
      - name: Tri-Cities Mesh Operators Discord
        url: joshuacarmack/tricitiesmesh
        icon: fab fa-discord
        desc: Discussion and help from your fellow users
    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    developer:
      - name: GitHub
        url: https://github.com/joshuacarmack/tricitiesmesh
        icon: fab fa-github
        desc: Development takes place here!

module:
  replacements: "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."
  imports:
    - path: github.com/google/docsy
  mounts:
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: content
      target: content
    - source: assets
      target: assets