media_folder: "static/uploads"

publish_mode: editorial_workflow

backend:
  name: github
  repo: joshuacarmack/tricitiesmesh.github.io
  branch: main
  base_url: https://decap.tricitiesmesh.pages.dev

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: content/blog
    path: "{{slug}}/index"
    nested:
      depth: 5
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: docs
    label: Docs
    label_singular: Doc
    folder: content/docs
    path: "{{slug}}/index"
    nested:
      depth: 5
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: nodes
    label: Nodes
    label_singular: Node
    folder: content/nodes
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "LoRa"
        name: "lora"
        widget: "object"
        fields:
          - { label: "Short Name", name: "shortName", widget: "string" }
          - { label: "Long Name", name: "longName", widget: "string" }
          - { label: "Device Mode", name: "mode", widget: "string" }
          - { label: "Node Number", name: "nodeNumber", widget: "number" }
      - label: "Location"
        name: "location"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Latitude", name: "latitude", widget: "number" }
          - { label: "Longitude", name: "longitude", widget: "number" }
          - { label: "Above Ground Level (m)", name: "agl", widget: "number" }
          - { label: "Altitude (m)", name: "altitude", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
